### ISSUE TITLE
Suppressing LangTool on Org-Mode LaTeX fragments

### ISSUE THREAD

**Issue by MeetThePatel** [cjl8zf/langtool-ignore-fonts#1]
In Org-mode, you can embed Latex fragments, but the font-lock is not changed for the \begin{equation}...\end{equation} blocks.

Is there any way to have LangTool suppressed on these blocks of text?

**Comment by cjl8zf** [comment]
Hi, in Org-mode LaTeX fragments should be fontified with the face ``'org-latex-and-related`` if ``'org-src-fontify-natively`` is set to ``'t``. So, the following code should do what you want:
```
(setq org-src-fontify-natively t)
(add-hook 'org-mode-hook 'langtool-ignore-fonts-minor-mode)
(langtool-ignore-fonts-add 'org-mode '(org-latex-and-related))
```
